import { useState, type FormEvent } from 'react'
import type { Quest, Skill } from '../../models/life-rpg'
import { useLanguage } from '../../hooks/useLanguage'

export function QuestForm({quest,skills,onSave,onCancel}:{quest?:Quest;skills:Skill[];onSave:(quest:Quest)=>void;onCancel:()=>void}){
  const {t,localize}=useLanguage()
  const [titleZh,setTitleZh]=useState(quest?.title.zh??'');const [titleEn,setTitleEn]=useState(quest?.title.en??'')
  const [descriptionZh,setDescriptionZh]=useState(quest?.description.zh??'');const [descriptionEn,setDescriptionEn]=useState(quest?.description.en??'')
  const [linkedSkillId,setLinkedSkillId]=useState(quest?.linkedSkillId??'');const [xpReward,setXpReward]=useState(String(quest?.xpReward??15));const [difficulty,setDifficulty]=useState<Quest['difficulty']>(quest?.difficulty??'normal');const [error,setError]=useState('')
  const submit=(event:FormEvent)=>{event.preventDefault();if(!titleZh.trim()||!titleEn.trim()){setError(t('requiredField'));return}const xp=Number(xpReward);if(!Number.isInteger(xp)||xp<1||xp>500){setError(t('invalidXP'));return}const linked=skills.find(skill=>skill.id===linkedSkillId);onSave({id:quest?.id??crypto.randomUUID(),title:{zh:titleZh.trim(),en:titleEn.trim()},description:{zh:descriptionZh.trim(),en:descriptionEn.trim()},linkedSkillId:linkedSkillId||undefined,xpReward:xp,difficulty,category:linked?.category,completed:quest?.completed??false,completedAt:quest?.completedAt,completionReward:quest?.completionReward,createdAt:quest?.createdAt??new Date().toISOString()})}
  return <form className="quest-form" onSubmit={submit}><div className="form-grid"><label><span>{t('questTitleZh')} *</span><input value={titleZh} onChange={event=>setTitleZh(event.target.value)}/></label><label><span>{t('questTitleEn')} *</span><input value={titleEn} onChange={event=>setTitleEn(event.target.value)}/></label><label><span>{t('questDescriptionZh')}</span><textarea rows={3} value={descriptionZh} onChange={event=>setDescriptionZh(event.target.value)}/></label><label><span>{t('questDescriptionEn')}</span><textarea rows={3} value={descriptionEn} onChange={event=>setDescriptionEn(event.target.value)}/></label><label><span>{t('linkedSkill')}</span><select value={linkedSkillId} onChange={event=>setLinkedSkillId(event.target.value)}><option value="">{t('noLinkedSkill')}</option>{skills.map(skill=><option key={skill.id} value={skill.id}>{localize(skill.name)}</option>)}</select></label><label><span>{t('xpRewardLabel')}</span><input type="number" min="1" max="500" step="1" value={xpReward} onChange={event=>setXpReward(event.target.value)}/></label><label><span>{t('difficulty')}</span><select value={difficulty} onChange={event=>setDifficulty(event.target.value as Quest['difficulty'])}>{(['easy','normal','hard','epic'] as const).map(value=><option value={value} key={value}>{t(value)}</option>)}</select></label></div>{quest?.completed&&<p className="completed-edit-note">{t('completedRewardNote')}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="text-button" onClick={onCancel}>{t('cancel')}</button><button className="primary-button" type="submit">{t('save')}</button></div></form>
}
