const targets = await fetch('http://127.0.0.1:9555/json').then((response) => response.json())
const page = targets.find((target) => target.type === 'page' && target.url.includes('127.0.0.1:5181'))
if (!page) throw new Error('No Life RPG browser page found')
const socket = new WebSocket(page.webSocketDebuggerUrl)
await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true})})
let id=0;const pending=new Map()
socket.addEventListener('message',(event)=>{const message=JSON.parse(event.data);if(!message.id||!pending.has(message.id))return;const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result)})
const call=(method,params={})=>new Promise((resolve,reject)=>{const requestId=++id;pending.set(requestId,{resolve,reject});socket.send(JSON.stringify({id:requestId,method,params}))})
const evaluate=async(expression)=>{const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result.value}
const wait=(ms)=>new Promise(resolve=>setTimeout(resolve,ms))
const click=async(selector,contains)=>evaluate(`{const items=[...document.querySelectorAll('${selector}')];const item=${contains?`items.find(item=>item.textContent.includes(${JSON.stringify(contains)}))`:'items[0]'};item?.click();Boolean(item)}`)
const snapshot=()=>evaluate(`({url:location.pathname,detail:document.querySelector('.detail-progress')?.innerText,node:document.querySelector('.skill-node.selected')?.innerText,language:document.documentElement.lang,stored:JSON.parse(localStorage.getItem('life-rpg:state')).skills.find(skill=>skill.id==='python')})`)
const setCustom=async(value)=>evaluate(`{const input=document.querySelector('.custom-xp input');const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(input,'${value}');input.dispatchEvent(new Event('input',{bubbles:true}))}`)
await call('Runtime.enable');await wait(500);await evaluate(`localStorage.removeItem('life-rpg:state')`);await call('Page.reload',{ignoreCache:true});await wait(1000)
const opened=await snapshot()
await click('.quick-xp button','+25 XP');await wait(250);const added25=await snapshot()
await click('.main-nav a','Dashboard');await wait(350);const dashboard=await evaluate(`({python:[...document.querySelectorAll('.skill-strip article')].find(item=>item.textContent.includes('Python'))?.innerText})`)
await click('.main-nav a','Skill Tree');await wait(350);await call('Page.reload',{ignoreCache:true});await wait(900);const persisted=await snapshot()
await setCustom(150);await click('.custom-xp button');await wait(300);const levelUp=await snapshot()
await setCustom(9999);await evaluate(`document.querySelectorAll('.custom-xp button')[1]?.click()`);await wait(300);const floor=await snapshot()
await click('.language-toggle button','EN');await wait(200);const english=await evaluate(`({language:document.documentElement.lang,title:document.querySelector('.skill-page-header h1')?.innerText,descriptionHeading:[...document.querySelectorAll('.detail-section h3')].map(item=>item.textContent)})`)
await click('.unlock-button, .lock-button','Lock skill');await wait(250);const locked=await snapshot();await call('Page.reload',{ignoreCache:true});await wait(900);const lockPersisted=await snapshot()
await click('.skill-filters button','Languages');await wait(250);const categoryFilter=await evaluate(`({count:document.querySelectorAll('.skill-node').length,names:[...document.querySelectorAll('.skill-node .node-copy strong')].map(item=>item.textContent)})`)
console.log(JSON.stringify({opened,added25,dashboard,persisted,levelUp,floor,english,locked,lockPersisted,categoryFilter},null,2));await call('Browser.close');socket.close()
